language: java
jdk: oraclejdk8

# before_script: cd project
before_install: cd backend
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dskip.npm=true -Dskip.bower=true -Dskip.gulp=true -B -V
script: mvn clean test -Dskip.npm=true -Dskip.bower=true -Dskip.gulp=true
